# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rpaper.core.fields.hashids
import thumbnailfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('hashid', rpaper.core.fields.hashids.HashidsField(hashids_min_length=8, hashids_salt='this should be a uniq long secret string:reservations:instrument', primary_key=True, serialize=False, verbose_name='Hashids')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('thumbnail', thumbnailfield.fields.ThumbnailField(blank=True, upload_to='reservations/instrument/thumbnails', verbose_name='Thumbnail')),
                ('ipaddress', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IPAddress')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'Instruments',
                'verbose_name': 'Instrument',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('hashid', rpaper.core.fields.hashids.HashidsField(hashids_min_length=8, hashids_salt='this should be a uniq long secret string:reservations:reservation', primary_key=True, serialize=False, verbose_name='Hashid')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('contact', models.CharField(max_length=255, verbose_name='Contact')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(verbose_name='End at')),
                ('credential', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Credential')),
                ('ipaddress', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IPAddress')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.Instrument', verbose_name='Instrument')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('start_at', 'end_at', 'name'),
                'verbose_name_plural': 'Reservations',
                'verbose_name': 'Reservation',
            },
        ),
    ]
